#!/bin/sh
set -e

# for kernel rebuilds
ulimit -f 2097152

# pushd ~/dotfiles/nixos/
nvim configuration.nix
# alejandra . &>/dev/null
git diff -U0 *.nix
echo "NixOS Rebuilding..."
sudo nixos-rebuild switch -v --flake --pure ./#default 
#&>nixos-switch.log || (
# cat nixos-switch.log | grep --color error && false)
#gen=$(nixos-rebuild list-generations | grep current)
#git commit -am "$gen"
# popd
